- platform: template
  switches:
    watch_tv:
      friendly_name: LivingRoom TiVo
      value_template: "{{ is_state_attr('remote.harmony_living_room_hub', 'current_activity', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.harmony_living_room_watch_tivo
      turn_off:
        service: script.turn_on
        entity_id: script.harmony_living_room_power_off
    watch_appletv:
      friendly_name: LivingRoom Apple TV
      value_template: "{{ is_state_attr('remote.harmony_living_room_hub', 'current_activity', 'on') }}"
      turn_on:
        service: script.turn_on
        entity_id: script.harmony_living_room_watch_appletv
      turn_off:
        service: script.turn_on
        entity_id: script.harmony_living_room_power_off        