- platform: group
  name: Bathroom Lights
  entities:
    - light.bathroom_1
    - light.bathroom_2
    - light.bathroom_3

- platform: group
  name: Living Room Lights
  entities:
    - light.floor_bloom
    - light.table_left
    - light.table_right

- platform: group
  name: Computer Room Lights
  entities:
    - light.desk_light


# THis is for the led strips using the ESP devices.
- platform: flux_led
  devices:
    192.168.1.122:
      name: Desk Light
