- alias: Bathroom Light Automation
  trigger:
  - platform: state
    entity_id: light.bathroom_1
    to: 'on'
  action:
    - service: script.turn_on
      entity_id: script.bathroom_light_control
    - delay: '00:00:03'
    - service: script.turn_on
      entity_id: script.bathroom_light_control
    - delay: '00:00:03'
    - service: script.turn_on
      entity_id: script.bathroom_light_control
