# @6:30 AM every morning, turn the morning light group on switch
# 20% Brightness and set to the Relax Profile (6AM/PM Sun Color)
- alias: Morning Light
  trigger:
    platform: sun
    event: "sunrise"
    offset: "00:00"
  action:
    service: light.turn_on
    entity_id: light.bedroom_light
    data:
      brightness_pct: 30
      transition: 1800

# @8:30 AM every morning, turn the morning light group off
- alias: Morning Light Off
  trigger:
    platform: time
    at: '07:00:00'
  action:
    service: light.turn_off
    entity_id: light.bedroom_light
    data:
      transition: 300

# Motion Detection between 7AM and 11:30PM
- alias: Bedroom Motion Detection Automation On
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bed_room_motion_sensor
    to: 'on'
  condition:
    condition: time
    after: '07:00'
    before: '23:30'
  action:
    service: homeassistant.turn_on
    entity_id: light.bedroom_light
    data:
      brightness_pct: 40

# Motion Detection Off, trasnition light to off if the motion state is off
# for 2 minutes
- alias: Bedroom Motion Detection Automation Off
  initial_state: true
  trigger:
    platform: state
    entity_id: binary_sensor.bed_room_motion_sensor
    to: 'off'
    for:
      minutes: 2
  action:
    service: homeassistant.turn_off
    entity_id: light.bedroom_light
    data:
      transition: 180
