# @6:30 AM every morning, turn the morning light group on switch
# 20% Brightness and set to the Relax Profile (6AM/PM Sun Color)
- alias: Morning Lights On
  initial_state: 'on'
  trigger:
    platform: sun
    event: "sunrise"
    offset: "-00:15:00"
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
    data:
      brightness_pct: 30
      transition: 1800

# @8:30 AM every morning, turn the morning light group off
- alias: Morning Lights Off
  initial_state: 'on'
  trigger:
    platform: time
    at: '8:30'
  action:
    service: light.turn_off
    entity_id: light.living_room_lights
    data:
      transition: 600

# 1/2hr before sunset turn the lights on, turn the morning light group on switch
# 20% Brightness and set to the Relax Profile (6AM/PM Sun Color)
- alias: Evening Lights On
  initial_state: 'on'
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
    data:
      brightness_pct: 40
      color_name: Orange
      transition: 1800

- alias: Evening Lights Off
  initial_state: 'on'
  trigger:
    - platform: time
      at: '21:30:00'
  action:
    service: light.turn_off
    entity_id: light.living_room_lights
    data:
      transition: 600
