# @6:30 AM every morning, turn the morning light group on switch
# 20% Brightness and set to the Relax Profile (6AM/PM Sun Color)
- alias: Morning Lights On
  initial_state: 'on'
  hide_entity: false
  trigger:
    platform: time
    at: '6:30'
  action:
    service: light.turn_on
    entity_id: light.living_room_lights, light.bedroom_light
    #light.floor_bloom, light.table_left, light.table_right
    data:
      brightness_pct: 40
      transition: 300

# @8:30 AM every morning, turn the morning light group off
- alias: Morning Lights Off
  initial_state: 'on'
  hide_entity: true
  trigger:
    platform: time
    at: '8:30'
  action:
    service: light.turn_off
    entity_id: light.living_room_lights, light.bedroom_light
    data:
      transition: 300

# 1/2hr before sunset turn the lights on, turn the morning light group on switch
# 20% Brightness and set to the Relax Profile (6AM/PM Sun Color)
- alias: Evening Lights On
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:30:00'
  action:
    service: light.turn_on
    entity_id: light.living_room_lights
    data:
      brightness_pct: 30
      rgb_color: [255,182,109] # Orange Hue
      transition: 300

- alias: Evening Lights Off
  initial_state: 'on'
  hide_entity: true
  trigger:
    - platform: time
      at: '21:30:00'
  action:
    service: light.turn_on
    entity_id: light.living_room_group
    data:
      brightness_pct: 30
      rgb_color: [255,182,109] # Orange Hue
      transition: 300
